library(pkgmaker)
library(rngtools)
library(registry)
library(digest)
library(grid)
library(NMF)
maMatrice=GetMatriceNotationsOuvragesV2()
#maMAtrice=ObtenirMatriceCategorieSocioProfFoisUtilisateur()
res=nmf(maMAtrice, 4)
w <- basis(res)
dim(w)
h <- coef(res)
dim(h)